/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/lib/sanity/schema.json
export type SanityImageAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Seo = {
	_type: 'seo';
	metaTitle?: string;
	metaDescription?: string;
	ogImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	noIndex?: boolean;
};

export type BlockContent = Array<
	| {
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: 'span';
				_key: string;
			}>;
			style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote';
			listItem?: 'bullet' | 'number';
			markDefs?: Array<{
				href: string;
				blank?: boolean;
				_type: 'link';
				_key: string;
			}>;
			level?: number;
			_type: 'block';
			_key: string;
	  }
	| {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt: string;
			caption?: string;
			_type: 'image';
			_key: string;
	  }
	| ({
			_key: string;
	  } & Code)
>;

export type SiteSettings = {
	_id: string;
	_type: 'siteSettings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	tagline?: string;
	description?: string;
	contactEmail?: string;
	logo?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
	favicon?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	titleTemplate?: string;
	defaultOgImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	socialLinks?: Array<{
		label: string;
		url: string;
		_key: string;
	}>;
	primaryNav?: Array<{
		label: string;
		href: string;
		_key: string;
	}>;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top: number;
	bottom: number;
	left: number;
	right: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x: number;
	y: number;
	height: number;
	width: number;
};

export type Category = {
	_id: string;
	_type: 'category';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	description?: string;
};

export type Slug = {
	_type: 'slug';
	current: string;
	source?: string;
};

export type Person = {
	_id: string;
	_type: 'person';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name: string;
	slug: Slug;
	kind?: 'internal' | 'external';
	role?: string;
	image?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
	bio?: string;
	email?: string;
	socialLinks?: Array<{
		label: string;
		url: string;
		_key: string;
	}>;
};

export type PersonReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'person';
};

export type CategoryReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'category';
};

export type SanityFileAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type Paper = {
	_id: string;
	_type: 'paper';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	authors?: Array<
		{
			_key: string;
		} & PersonReference
	>;
	darcstarAuthored?: boolean;
	status?: 'draft' | 'preprint' | 'toAppear' | 'published';
	abstract?: string;
	categories?: Array<
		{
			_key: string;
		} & CategoryReference
	>;
	venue?: string;
	publishedDate?: string;
	url?: string;
	doi?: string;
	arxivId?: string;
	codeUrl?: string;
	pdf?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	seo?: Seo;
};

export type PaperReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'paper';
};

export type Post = {
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	language?: string;
	excerpt?: string;
	authors?: Array<
		{
			_key: string;
		} & PersonReference
	>;
	categories?: Array<
		{
			_key: string;
		} & CategoryReference
	>;
	relatedPapers?: Array<
		{
			_key: string;
		} & PaperReference
	>;
	publishedAt: string;
	featured?: boolean;
	coverImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		_type: 'image';
	};
	body?: BlockContent;
	seo?: Seo;
};

export type Code = {
	_type: 'code';
	language?: string;
	filename?: string;
	code?: string;
	highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height: number;
	width: number;
	aspectRatio: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	thumbHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash: string;
	extension: string;
	mimeType: string;
	size: number;
	assetId: string;
	uploadId?: string;
	path: string;
	url: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash: string;
	extension: string;
	mimeType: string;
	size: number;
	assetId: string;
	uploadId?: string;
	path: string;
	url: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| SanityImageAssetReference
	| Seo
	| BlockContent
	| SiteSettings
	| SanityImageCrop
	| SanityImageHotspot
	| Category
	| Slug
	| Person
	| PersonReference
	| CategoryReference
	| SanityFileAssetReference
	| Paper
	| PaperReference
	| Post
	| Code
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: postsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {		_id,		title,		"slug": slug.current,		excerpt,		publishedAt,		featured,		coverImage,		authors[]->{ _id, name, "slug": slug.current, role }	}
export type PostsQueryResult = Array<{
	_id: string;
	title: string;
	slug: string;
	excerpt: string | null;
	publishedAt: string;
	featured: boolean | null;
	coverImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		_type: 'image';
	} | null;
	authors: Array<{
		_id: string;
		name: string;
		slug: string;
		role: string | null;
	}> | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {		_id,		title,		"slug": slug.current,		excerpt,		publishedAt,		coverImage,		body,		authors[]->{ _id, name, "slug": slug.current, role, image },		categories[]->{ _id, title, "slug": slug.current },		relatedPapers[]->{ _id, title, "slug": slug.current, venue },		seo	}
export type PostBySlugQueryResult = {
	_id: string;
	title: string;
	slug: string;
	excerpt: string | null;
	publishedAt: string;
	coverImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		_type: 'image';
	} | null;
	body: BlockContent | null;
	authors: Array<{
		_id: string;
		name: string;
		slug: string;
		role: string | null;
		image: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			_type: 'image';
		} | null;
	}> | null;
	categories: Array<{
		_id: string;
		title: string;
		slug: string;
	}> | null;
	relatedPapers: Array<{
		_id: string;
		title: string;
		slug: string;
		venue: string | null;
	}> | null;
	seo: Seo | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: papersQuery
// Query: *[_type == "paper" && defined(slug.current)] | order(publishedDate desc) {		_id,		title,		"slug": slug.current,		status,		darcstarAuthored,		venue,		publishedDate,		url,		doi,		arxivId,		codeUrl,		abstract,		authors[]->{ _id, name, "slug": slug.current }	}
export type PapersQueryResult = Array<{
	_id: string;
	title: string;
	slug: string;
	status: 'draft' | 'preprint' | 'published' | 'toAppear' | null;
	darcstarAuthored: boolean | null;
	venue: string | null;
	publishedDate: string | null;
	url: string | null;
	doi: string | null;
	arxivId: string | null;
	codeUrl: string | null;
	abstract: string | null;
	authors: Array<{
		_id: string;
		name: string;
		slug: string;
	}> | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: paperBySlugQuery
// Query: *[_type == "paper" && slug.current == $slug][0] {		_id,		title,		"slug": slug.current,		status,		darcstarAuthored,		abstract,		venue,		publishedDate,		url,		doi,		arxivId,		codeUrl,		"pdfUrl": pdf.asset->url,		authors[]->{ _id, name, "slug": slug.current, role },		categories[]->{ _id, title, "slug": slug.current },		seo	}
export type PaperBySlugQueryResult = {
	_id: string;
	title: string;
	slug: string;
	status: 'draft' | 'preprint' | 'published' | 'toAppear' | null;
	darcstarAuthored: boolean | null;
	abstract: string | null;
	venue: string | null;
	publishedDate: string | null;
	url: string | null;
	doi: string | null;
	arxivId: string | null;
	codeUrl: string | null;
	pdfUrl: string | null;
	authors: Array<{
		_id: string;
		name: string;
		slug: string;
		role: string | null;
	}> | null;
	categories: Array<{
		_id: string;
		title: string;
		slug: string;
	}> | null;
	seo: Seo | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: peopleQuery
// Query: *[_type == "person" && kind != "external"] | order(name asc) {		_id,		name,		"slug": slug.current,		role,		image,		bio,		socialLinks[]{ label, url }	}
export type PeopleQueryResult = Array<{
	_id: string;
	name: string;
	slug: string;
	role: string | null;
	image: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	} | null;
	bio: string | null;
	socialLinks: Array<{
		label: string;
		url: string;
	}> | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		'\n\t*[_type == "post" && defined(slug.current)] | order(publishedAt desc) {\n\t\t_id,\n\t\ttitle,\n\t\t"slug": slug.current,\n\t\texcerpt,\n\t\tpublishedAt,\n\t\tfeatured,\n\t\tcoverImage,\n\t\tauthors[]->{ _id, name, "slug": slug.current, role }\n\t}\n': PostsQueryResult;
		'\n\t*[_type == "post" && slug.current == $slug][0] {\n\t\t_id,\n\t\ttitle,\n\t\t"slug": slug.current,\n\t\texcerpt,\n\t\tpublishedAt,\n\t\tcoverImage,\n\t\tbody,\n\t\tauthors[]->{ _id, name, "slug": slug.current, role, image },\n\t\tcategories[]->{ _id, title, "slug": slug.current },\n\t\trelatedPapers[]->{ _id, title, "slug": slug.current, venue },\n\t\tseo\n\t}\n': PostBySlugQueryResult;
		'\n\t*[_type == "paper" && defined(slug.current)] | order(publishedDate desc) {\n\t\t_id,\n\t\ttitle,\n\t\t"slug": slug.current,\n\t\tstatus,\n\t\tdarcstarAuthored,\n\t\tvenue,\n\t\tpublishedDate,\n\t\turl,\n\t\tdoi,\n\t\tarxivId,\n\t\tcodeUrl,\n\t\tabstract,\n\t\tauthors[]->{ _id, name, "slug": slug.current }\n\t}\n': PapersQueryResult;
		'\n\t*[_type == "paper" && slug.current == $slug][0] {\n\t\t_id,\n\t\ttitle,\n\t\t"slug": slug.current,\n\t\tstatus,\n\t\tdarcstarAuthored,\n\t\tabstract,\n\t\tvenue,\n\t\tpublishedDate,\n\t\turl,\n\t\tdoi,\n\t\tarxivId,\n\t\tcodeUrl,\n\t\t"pdfUrl": pdf.asset->url,\n\t\tauthors[]->{ _id, name, "slug": slug.current, role },\n\t\tcategories[]->{ _id, title, "slug": slug.current },\n\t\tseo\n\t}\n': PaperBySlugQueryResult;
		'\n\t*[_type == "person" && kind != "external"] | order(name asc) {\n\t\t_id,\n\t\tname,\n\t\t"slug": slug.current,\n\t\trole,\n\t\timage,\n\t\tbio,\n\t\tsocialLinks[]{ label, url }\n\t}\n': PeopleQueryResult;
	}
}
