import { describe, expect, test } from 'vitest';
import { betterAuth } from 'better-auth/minimal';
import { memoryAdapter } from 'better-auth/adapters/memory';
import { admin } from 'better-auth/plugins';
import { ACTIVATION_CALLBACK_PATH, mintActivationLink } from './activation';
import { ACTIVATION_TOKEN_TTL_SECONDS, RESET_PASSWORD_TOKEN_TTL_SECONDS } from './auth-options';

// THIS SPEC IS THE PIN FOR A DELIBERATE COUPLING. `mintActivationLink` writes a `verification` row
// under better-auth's own `reset-password:<token>` identifier convention — an internal detail, not a
// public API — so that an invite link is redeemable by the existing /reset-password flow instead of
// needing a second credential-setting path. The trade is that a better-auth upgrade could rename the
// prefix and every invite would dead-end at "invalid link" with nothing failing in CI.
//
// So these tests never assert the prefix. They mint through OUR code and redeem through BETTER-AUTH's
// (`auth.api.resetPassword`, the very endpoint /reset-password posts to), which fails the moment the
// two stop agreeing, whatever the reason.
//
// Backed by a memory adapter, so it's hermetic: no DB, no env, no Resend, no request context.
function buildAuth() {
	return betterAuth({
		baseURL: 'http://localhost',
		secret: 'test-secret-value-at-least-32-characters-long',
		database: memoryAdapter({ user: [], session: [], account: [], verification: [] }),
		// `sendResetPassword` has to exist or better-auth disables the reset endpoints entirely
		// (password.mjs) — the invite never calls it, but the redemption half of the flow needs them
		// live. Verification is left off so a test can sign in and prove a password actually works.
		emailAndPassword: { enabled: true, sendResetPassword: async () => {} },
		// The invite action creates accounts through this plugin, so the end-to-end test below needs it.
		plugins: [admin({ adminRoles: ['admin'], defaultRole: 'user' })]
	});
}

// The unguessable password the invite action generates and nobody is ever shown.
const PLACEHOLDER = 'placeholder-password-nobody-knows';
// What the invitee picks when they follow the link.
const CHOSEN = 'the-password-they-chose';

/** Pull the token out of an activation URL (…/api/auth/reset-password/<token>?callbackURL=…). */
function tokenFromUrl(url: string): string {
	const path = new URL(url).pathname;
	return path.slice(path.lastIndexOf('/') + 1);
}

async function inviteeAccount(auth: ReturnType<typeof buildAuth>, email: string) {
	const created = await auth.api.signUpEmail({
		body: { name: 'Ada', email, password: PLACEHOLDER }
	});
	return created.user.id;
}

describe('mintActivationLink', () => {
	// The whole point of the feature: someone who has never had a password ends up with one they chose,
	// and the random one the invite action minted for them stops working.
	test('the minted link redeems through better-auth and sets a working password', async () => {
		const auth = buildAuth();
		const userId = await inviteeAccount(auth, 'invitee@example.com');

		const link = await mintActivationLink(auth, userId);
		const res = await auth.api.resetPassword({
			body: { newPassword: CHOSEN, token: tokenFromUrl(link.url) }
		});
		expect(res.status).toBe(true);

		const signIn = await auth.api.signInEmail({
			body: { email: 'invitee@example.com', password: CHOSEN }
		});
		expect(signIn.user.email).toBe('invitee@example.com');
		// The placeholder the operator never saw is now dead — otherwise a password generated by the
		// server, logged nowhere but existing forever, would remain a valid credential.
		await expect(
			auth.api.signInEmail({ body: { email: 'invitee@example.com', password: PLACEHOLDER } })
		).rejects.toThrow();
	});

	// Following the emailed link for real: GET the URL we actually put in the mail and confirm
	// better-auth validates the token and forwards to the page, with the invite flag intact. This is
	// the half a token-only test can't see — a wrong base path or a mangled callbackURL 404s here.
	test('GETting the emailed URL redirects to the invite-flagged reset page with the token', async () => {
		const auth = buildAuth();
		const userId = await inviteeAccount(auth, 'redirect@example.com');

		const link = await mintActivationLink(auth, userId);
		const res = await auth.handler(new Request(link.url, { method: 'GET' }));

		expect(res.status).toBe(302);
		const location = res.headers.get('location') ?? '';
		expect(location).toContain(ACTIVATION_CALLBACK_PATH);
		expect(new URL(location, 'http://localhost').searchParams.get('token')).toBe(
			tokenFromUrl(link.url)
		);
	});

	// Single-use, inherited from the reset flow rather than reimplemented. An activation link that
	// survived redemption would sit in a mailbox as a standing account-takeover primitive.
	test('the link is single-use', async () => {
		const auth = buildAuth();
		const userId = await inviteeAccount(auth, 'once@example.com');

		const token = tokenFromUrl((await mintActivationLink(auth, userId)).url);
		await auth.api.resetPassword({ body: { newPassword: CHOSEN, token } });
		await expect(
			auth.api.resetPassword({ body: { newPassword: 'another-password-entirely', token } })
		).rejects.toThrow(/token/i);
	});

	// A resend has to invalidate nothing and mint fresh — two invites in flight must not collide, and
	// a token that repeated across mints would be guessable from a single leaked email.
	test('each mint is a distinct token, and a resend redeems independently', async () => {
		const auth = buildAuth();
		const userId = await inviteeAccount(auth, 'resend@example.com');

		const first = await mintActivationLink(auth, userId);
		const second = await mintActivationLink(auth, userId);
		expect(tokenFromUrl(first.url)).not.toBe(tokenFromUrl(second.url));

		const res = await auth.api.resetPassword({
			body: { newPassword: CHOSEN, token: tokenFromUrl(second.url) }
		});
		expect(res.status).toBe(true);
	});

	// The email tells the recipient "expires in seven days". This is the other end of that sentence.
	test('expiry is the week-long activation TTL, not the hour-long reset one', async () => {
		const auth = buildAuth();
		const userId = await inviteeAccount(auth, 'ttl@example.com');

		const before = Date.now();
		const link = await mintActivationLink(auth, userId);
		const ttlMs = link.expiresAt.getTime() - before;

		expect(ACTIVATION_TOKEN_TTL_SECONDS).toBe(604_800);
		expect(ttlMs).toBeGreaterThan(ACTIVATION_TOKEN_TTL_SECONDS * 1000 - 5_000);
		expect(ttlMs).toBeLessThanOrEqual(ACTIVATION_TOKEN_TTL_SECONDS * 1000);
		// The two are deliberately different numbers: an unrequested invitation gets a week, a reset the
		// visitor just asked for keeps its hour. If someone collapses them back into one constant, this
		// is the assertion that should stop them.
		expect(ACTIVATION_TOKEN_TTL_SECONDS).toBeGreaterThan(RESET_PASSWORD_TOKEN_TTL_SECONDS);
	});

	// THE PROPERTY THE WEEK-LONG TTL RESTS ON. `resetPasswordTokenExpiresIn` (an hour) is still what
	// better-auth's own `requestPasswordReset` stamps, so if consumption recomputed expiry from that
	// config instead of reading the row, every invitation would silently die after an hour while the
	// email promised a week — and nothing else in this suite would notice, because a fresh token passes
	// either way. Age the row past its expiry and prove better-auth rejects it.
	test('better-auth enforces expiry from the row, so the longer lifetime is real', async () => {
		const auth = buildAuth();
		const userId = await inviteeAccount(auth, 'expiry@example.com');

		const link = await mintActivationLink(auth, userId);
		const token = tokenFromUrl(link.url);
		const identifier = `reset-password:${token}`;

		// Reached through the context's own adapter rather than by holding a reference to the array
		// handed to `memoryAdapter`: that store is cloned on the first transactional write, so the
		// caller's array is orphaned as soon as anything else writes (the sign-up above does).
		const ctx = await auth.$context;
		const stored = await ctx.internalAdapter.findVerificationValue(identifier);
		expect(stored).not.toBeNull();
		// Stamped a week out — well past what `resetPasswordTokenExpiresIn` would have given it.
		expect(stored!.expiresAt.getTime() - Date.now()).toBeGreaterThan(
			RESET_PASSWORD_TOKEN_TTL_SECONDS * 1000
		);

		// Now age the row. If expiry came from anywhere but this field, the reset below would still
		// succeed — and every invitation would quietly die after an hour while the email promised a week.
		await ctx.adapter.update({
			model: 'verification',
			where: [{ field: 'identifier', value: identifier }],
			update: { expiresAt: new Date(Date.now() - 1_000) }
		});
		await expect(auth.api.resetPassword({ body: { newPassword: CHOSEN, token } })).rejects.toThrow(
			/token/i
		);
	});

	// THE PRODUCTION PATH, end to end. The invite action creates the account with NO password at all
	// (better-auth makes it optional and simply omits the credential record), so between the invite and
	// the click there is no credential anywhere that could be guessed, leaked or reused. This proves
	// the missing credential is CREATED on redemption rather than being a dead end — the one thing that
	// would break the entire flow, and the one thing the signUpEmail-based tests above can't see,
	// because those accounts already have a password to overwrite.
	test('an account created with no password at all becomes usable via the link', async () => {
		const auth = buildAuth();
		const created = await auth.api.createUser({
			body: {
				email: 'nopassword@example.com',
				name: 'Invitee',
				role: 'user',
				data: { emailVerified: true }
			}
		});

		// Nothing to sign in with yet — the account exists but is unusable, which is the point.
		await expect(
			auth.api.signInEmail({ body: { email: 'nopassword@example.com', password: CHOSEN } })
		).rejects.toThrow();

		const link = await mintActivationLink(auth, created.user.id);
		await auth.api.resetPassword({
			body: { newPassword: CHOSEN, token: tokenFromUrl(link.url) }
		});

		const signIn = await auth.api.signInEmail({
			body: { email: 'nopassword@example.com', password: CHOSEN }
		});
		expect(signIn.user.email).toBe('nopassword@example.com');
	});

	// A token in a URL path segment must survive being one: base64's `+` and `/` would not.
	test('the token is URL-safe and long enough to be unguessable', async () => {
		const auth = buildAuth();
		const userId = await inviteeAccount(auth, 'shape@example.com');

		const token = tokenFromUrl((await mintActivationLink(auth, userId)).url);
		expect(token).toMatch(/^[A-Za-z0-9_-]+$/);
		expect(token.length).toBeGreaterThanOrEqual(32);
		expect(encodeURIComponent(token)).toBe(token);
	});
});
