// Deterministic `worker-configuration.d.ts` generation (DAR-49). `wrangler types` on its own is
// checkout-dependent, which made the committed file drift and broke `pnpm check` on any tree
// without a `.env` (CI saw 19 phantom "not on type Env" errors). Three sources of nondeterminism:
//
//   1. Env-var NAMES come from whatever `.env` wrangler finds — absent in CI, and a dev's real
//      `.env` may carry extras (e.g. VITE_SANITY_DATASET). Fixed by pinning `--env-file` to the
//      committed `.env.example`, which fully REPLACES default .env discovery. That makes
//      `.env.example` the type-level source of truth: a new runtime var isn't typed until it's
//      listed there (which docs/deployment.md already requires).
//   2. The header comment embeds the exact CLI + a content hash. Rewritten to a stable line.
//   3. A `Cloudflare.GlobalProps` block appears only when the built worker
//      (.svelte-kit/cloudflare/_worker.js) exists, so output differed before vs after a build.
//      Stripped — nothing in src/ consumes it.
//
// Result: byte-identical output on every checkout. It changes only when a committed input does
// (wrangler.jsonc, .env.example, or the wrangler version), and the `check` CI job drift-guards
// the committed copy, so those changes must ship their regenerated types.

import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = join(root, 'worker-configuration.d.ts');

const result = spawnSync('pnpm', ['exec', 'wrangler', 'types', '--env-file=.env.example'], {
	cwd: root,
	stdio: ['ignore', 'ignore', 'inherit']
});
if (result.status !== 0) {
	console.error('gen-types: wrangler types failed');
	process.exit(result.status ?? 1);
}

let types = readFileSync(outFile, 'utf8');

// (2) Volatile header — the wrangler line carries the invocation + a hash of the pre-normalized
// content (which itself varies by (3)), so it can never be stable. One line in, one line out.
const header = /^\/\/ Generated by Wrangler by running .*$/m;
if (!header.test(types)) {
	console.error(
		'gen-types: expected the "Generated by Wrangler" header — wrangler output changed?'
	);
	process.exit(1);
}
types = types.replace(
	header,
	'// Generated by `pnpm gen` (scripts/gen-types.mjs) — deterministic: env-var names come from\n' +
		'// .env.example; volatile bits are normalized. Never run `wrangler types` directly.'
);

// (3) Build-output-dependent block. Tab-anchored on purpose: the project section is
// tab-indented, while the runtime-types section further down declares its own space-indented
// empty `GlobalProps` (a declaration-merge target) that must stay.
const globalProps = /\n\tinterface GlobalProps \{[\s\S]*?\n\t\}/;
types = types.replace(globalProps, '');
if (globalProps.test(types)) {
	console.error('gen-types: GlobalProps survived the strip — wrangler output changed?');
	process.exit(1);
}

writeFileSync(outFile, types);
console.log('gen-types: worker-configuration.d.ts regenerated (deterministic)');
