name: actionlint

on:
  push:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run actionlint
        uses: raven-actions/actionlint@v2
